export interface ThoughtSummary {
  id: string;
  createdAt: Date;
  content?: string;        // Markdown content (new format)
  title?: string;          // Extracted title for sidebar display (new format)
  
  // Legacy format compatibility
  subject?: string;
  background?: string;
  hypothesis?: string;
  analysis?: string;
  decision?: string;
  development?: string;
  insights?: string;
  output?: string;
}

export interface ApiResponse<T> {
  success: boolean;
  data?: T;
  error?: string;
}

export function generateMarkdownText(summary: ThoughtSummary): string {
  const date = new Date(summary.createdAt).toLocaleDateString('en-US', {
    year: 'numeric',
    month: 'long',
    day: 'numeric'
  });
  
  return `# ${summary.title} - ${date}

${summary.content}

---
*Generated by Scribble*`;
}

// Markdown content から title を抽出する関数
export function extractTitleFromMarkdown(content: string): string {
  const firstHeading = content.match(/^#\s+(.+)$/m);
  if (firstHeading) {
    return firstHeading[1].trim();
  }
  
  const subjectMatch = content.match(/##\s+Subject\s*\n([^\n]+)/i);
  if (subjectMatch) {
    return subjectMatch[1].trim();
  }
  
  return 'Untitled Summary';
}